

const data = [
    {
        rank: 1,
        name: {
            icon: "https://assets.coincap.io/assets/icons/btc@2x.png",
            assetName: "Bitcoin",
            abbreviation: "BTC",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 2,
        name: {
            icon: "https://assets.coincap.io/assets/icons/eth@2x.png",
            assetName: "Ethereum",
            abbreviation: "ETH",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 3,
        name: {
            icon: "https://assets.coincap.io/assets/icons/usdt@2x.png",
            assetName: "Tether",
            abbreviation: "TTH",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },

    {
        rank: 4,
        name: {
            icon: "https://assets.coincap.io/assets/icons/bnb@2x.png",
            assetName: "BNB",
            abbreviation: "BNB",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 5,
        name: {
            icon: "https://assets.coincap.io/assets/icons/usdc@2x.png",
            assetName: "USD Coin",
            abbreviation: "USD",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 6,
        name: {
            icon: "https://assets.coincap.io/assets/icons/xrp@2x.png",
            assetName: "XRP",
            abbreviation: "XRP",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 7,
        name: {
            icon: "https://assets.coincap.io/assets/icons/ada@2x.png",
            assetName: "Cardano",
            abbreviation: "ADA",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 8,
        name: {
            icon: "https://assets.coincap.io/assets/icons/matic@2x.png",
            assetName: "Polygon",
            abbreviation: "MATIC",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 9,
        name: {
            icon: "https://assets.coincap.io/assets/icons/doge@2x.png",
            assetName: "Dogecoin",
            abbreviation: "DOGE",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 10,
        name: {
            icon: "https://assets.coincap.io/assets/icons/busd@2x.png",
            assetName: "Binance USD",
            abbreviation: "BUSD",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 11,
        name: {
            icon: "https://assets.coincap.io/assets/icons/sol@2x.png",
            assetName: "Solana",
            abbreviation: "SOL",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    }, {
        rank: 12,
        name: {
            icon: "https://assets.coincap.io/assets/icons/dot@2x.png",
            assetName: "Polkadot",
            abbreviation: "DOT",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 13,
        name: {
            icon: "https://assets.coincap.io/assets/icons/ltc@2x.png",
            assetName: "Litecoin",
            abbreviation: "LTC",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 14,
        name: {
            icon: "https://assets.coincap.io/assets/icons/trx@2x.png",
            assetName: "TRON",
            abbreviation: "TRX",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 15,
        name: {
            icon: "https://assets.coincap.io/assets/icons/shib@2x.png",
            assetName: "Shiba Inu",
            abbreviation: "SHIB",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 16,
        name: {
            icon: "https://assets.coincap.io/assets/icons/avax@2x.png",
            assetName: "Avalanche",
            abbreviation: "AVX",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 17,
        name: {
            icon: "https://assets.coincap.io/assets/icons/dai@2x.png",
            assetName: "Multi Collateral DAI",
            abbreviation: "DAI",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 18,
        name: {
            icon: "https://assets.coincap.io/assets/icons/uni@2x.png",
            assetName: "Uniswap",
            abbreviation: "UNI",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 19,
        name: {
            icon: "https://assets.coincap.io/assets/icons/link@2x.png",
            assetName: "Chainlink",
            abbreviation: "LINK",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
    {
        rank: 20,
        name: {
            icon: "https://assets.coincap.io/assets/icons/wbtc@2x.png",
            assetName: "Wrapped Bitcoin",
            abbreviation: "  WBTC",
        },
        price: "$22,536.85",
        marketCap: "$435.17b",
        vWap: "$22,407.12",
        supply: "-1.70b",
        volume: "$224.63k",
        change: "-2.68%",
    },
]
export default data;

